adds a reference to the object type Collections
godror/godror pull request #122
Opened 2020-12-22 19:49 UTC by wwanderley

Adds a reference to object type to avoid SIGABRT like:

```
free(): corrupted unsorted chunks
SIGABRT: abort
PC=0x7fcc67d88c81 m=11 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fcc67d88c81
stack: frame={sp:0x7fcc22ffc9f0, fp:0x0} stack=[0x7fcc227fd288,0x7fcc22ffce88)
00007fcc22ffc8f0:  0000000000000000  0000000000000000 
00007fcc22ffc900:  0000000000000000  0000000000000000 
00007fcc22ffc910:  00007fcc22ffc990  00007fcc187033c5 
00007fcc22ffc920:  00007fcc340ae658  0000000000000000 
00007fcc22ffc930:  00007fcc340c0d00  0000000000000001 
00007fcc22ffc940:  00007fcc34145630  00007fcc22ffc9e0 
00007fcc22ffc950:  00000000000000fb  00007fcc22ffc9e0 
00007fcc22ffc960:  0000000000000000  0000000000000001 
00007fcc22ffc970:  0000000000000000  0000000000000000 
00007fcc22ffc980:  00007fcc340ae658  00007fcc22ffcaa8 
00007fcc22ffc990:  00007fcc22ffca40  00007fcc1887239f 
00007fcc22ffc9a0:  0000000000000001  00007fcc34145630 
00007fcc22ffc9b0:  00007fcc340ae658  0000000000000000 
00007fcc22ffc9c0:  00007fcc22ffca10  00007fcc18867adf 
00007fcc22ffc9d0:  00007fcc34159678  00007fcc34161a38 
00007fcc22ffc9e0:  00007fcc34161a40  00007fcc1b41a35c 
00007fcc22ffc9f0: <0000000000000000  00007fcc340ae658 
00007fcc22ffca00:  0000000000000000  00007fcc34103828 
00007fcc22ffca10:  00007fcc22ffca60  00007fcc188679ed 
00007fcc22ffca20:  00007fcc34145630  00007fcc340ae658 
00007fcc22ffca30:  00007fcc22ffcb00  00007fcc1b41a35c 
00007fcc22ffca40:  00007fcc34145630  00007fcc340ae658 
00007fcc22ffca50:  00007fcc22ffcb00  0000000000000000 
00007fcc22ffca60:  00007fcc22ffcae0  00007fcc188726a0 
00007fcc22ffca70:  fffffffe7fffffff  ffffffffffffffff 
00007fcc22ffca80:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffca90:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcaa0:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcab0:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcac0:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcad0:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcae0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7fcc67d88c81
stack: frame={sp:0x7fcc22ffc9f0, fp:0x0} stack=[0x7fcc227fd288,0x7fcc22ffce88)
00007fcc22ffc8f0:  0000000000000000  0000000000000000 
00007fcc22ffc900:  0000000000000000  0000000000000000 
00007fcc22ffc910:  00007fcc22ffc990  00007fcc187033c5 
00007fcc22ffc920:  00007fcc340ae658  0000000000000000 
00007fcc22ffc930:  00007fcc340c0d00  0000000000000001 
00007fcc22ffc940:  00007fcc34145630  00007fcc22ffc9e0 
00007fcc22ffc950:  00000000000000fb  00007fcc22ffc9e0 
00007fcc22ffc960:  0000000000000000  0000000000000001 
00007fcc22ffc970:  0000000000000000  0000000000000000 
00007fcc22ffc980:  00007fcc340ae658  00007fcc22ffcaa8 
00007fcc22ffc990:  00007fcc22ffca40  00007fcc1887239f 
00007fcc22ffc9a0:  0000000000000001  00007fcc34145630 
00007fcc22ffc9b0:  00007fcc340ae658  0000000000000000 
00007fcc22ffc9c0:  00007fcc22ffca10  00007fcc18867adf 
00007fcc22ffc9d0:  00007fcc34159678  00007fcc34161a38 
00007fcc22ffc9e0:  00007fcc34161a40  00007fcc1b41a35c 
00007fcc22ffc9f0: <0000000000000000  00007fcc340ae658 
00007fcc22ffca00:  0000000000000000  00007fcc34103828 
00007fcc22ffca10:  00007fcc22ffca60  00007fcc188679ed 
00007fcc22ffca20:  00007fcc34145630  00007fcc340ae658 
00007fcc22ffca30:  00007fcc22ffcb00  00007fcc1b41a35c 
00007fcc22ffca40:  00007fcc34145630  00007fcc340ae658 
00007fcc22ffca50:  00007fcc22ffcb00  0000000000000000 
00007fcc22ffca60:  00007fcc22ffcae0  00007fcc188726a0 
00007fcc22ffca70:  fffffffe7fffffff  ffffffffffffffff 
00007fcc22ffca80:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffca90:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcaa0:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcab0:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcac0:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcad0:  ffffffffffffffff  ffffffffffffffff 
00007fcc22ffcae0:  ffffffffffffffff  ffffffffffffffff 

goroutine 438 [syscall]:
runtime.cgocall(0xb230b0, 0xc00064b198, 0x82)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00064b168 sp=0xc00064b130 pc=0x4108cb
github.com/godror/godror._Cfunc_dpiObjectType_release(0x7fcc08048380, 0x7fcc00000000)
        _cgo_gotypes.go:3820 +0x49 fp=0xc00064b198 sp=0xc00064b168 pc=0x761fa9
github.com/godror/godror.(*ObjectType).Close.func1(0x7fcc08048380, 0xc00036e180)
        /home/walter/go/pkg/mod/github.com/godror/godror@v0.22.2/obj.go:494 +0x4d fp=0xc00064b1c8 sp=0xc00064b198 pc=0x79ff8d
github.com/godror/godror.(*ObjectType).Close(0xc000573580, 0x0, 0x0)
        /home/walter/go/pkg/mod/github.com/godror/godror@v0.22.2/obj.go:494 +0x40f fp=0xc00064b508 sp=0xc00064b1c8 pc=0x77cf8f
git.serpro/scc-acao-judicial/judi/internal/infrastructure/database.PrOrdenarPdcomp(0xe0cd80, 0xc00036e090, 0xdf8560, 0xc00036e0f0, 0xc0003aac20, 0x12, 0x1b6154, 0xbf1c01, 0xbcf4c0, 0xdf8860, ...)
```

This error occurs in a production system after some requests to a Stored Procedure that return a PL/SQL Collection.

2020-12-22 21:07 UTC, tgulacsi commented
Where will it be this reference decreased?
Does DPI_DEBUG_LEVEL=92 support this plus addRef ?

2020-12-22 22:25 UTC, wwanderley commented
I've got a different error but the cause remains the same:

```
DPI [04475] 2020-12-22 19:14:58.047: fn start dpiObjectType_release(0x7f9d4c169380)
ODPI [04475] 2020-12-22 19:14:58.047: fn end dpiObjectType_release(0x7f9d4c169380) -> 0
ODPI [04475] 2020-12-22 19:14:58.047: fn start dpiObjectType_release(0x7f9d4c1692f0)
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f9c4c000090 pc=0x7f9d961956b7]

runtime stack:
runtime.throw(0xd0129b, 0x2a)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 391 [syscall]:
runtime.cgocall(0xb230b0, 0xc00056d198, 0x0)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00056d168 sp=0xc00056d130 pc=0x4108cb
github.com/godror/godror._Cfunc_dpiObjectType_release(0x7f9d4c1692f0, 0x7f9d00000000)
        _cgo_gotypes.go:3820 +0x49 fp=0xc00056d198 sp=0xc00056d168 pc=0x761fa9
github.com/godror/godror.(*ObjectType).Close.func1(0x7f9d4c1692f0, 0xc000310cf0)
```

**0x7f9d4c169380** is the `Record Type` and **0x7f9d4c1692f0** is the `Table of`. Without AddRef the "Record Type" is freed before dpiObjectType_release execution of the "Table of".

SIGSEGV is raised after 4 or 5 executions.

2020-12-22 22:34 UTC, wwanderley commented
DPI_DEBUG_LEVEL=38

```
ODPI [06884] 2020-12-22 19:29:17.603: fn start dpiObjectType_release(0x7fbd4013a170)
ODPI [06884] 2020-12-22 19:29:17.603: ref 0x7fbd4013a170 (dpiObjectType) -> 0
ODPI [06884] 2020-12-22 19:29:17.603: ref 0x7fbd40131e00 (dpiConn) -> 2
ODPI [06884] 2020-12-22 19:29:17.603: freed ptr at 0x7fbd40121f10
ODPI [06884] 2020-12-22 19:29:17.603: freed ptr at 0x7fbd40118720
ODPI [06884] 2020-12-22 19:29:17.603: freed ptr at 0x7fbd4013a170
ODPI [06884] 2020-12-22 19:29:17.603: fn end dpiObjectType_release(0x7fbd4013a170) -> 0
ODPI [06884] 2020-12-22 19:29:17.603: fn start dpiObjectType_release(0x7fbd4013a0e0)
ODPI [06884] 2020-12-22 19:29:17.603: ref 0x7fbd4013a0e0 (dpiObjectType) -> 0
ODPI [06884] 2020-12-22 19:29:17.603: ref 0x7fbd40131e00 (dpiConn) -> 1
ODPI [06884] 2020-12-22 19:29:17.603: ref 0x7fbd4013a170 () -> 32700
```
0x7fbd4013a170 is the Record
0x7fbd4013a0e0 is the Tabe Of

Check the invalid ref at `ODPI [06884] 2020-12-22 19:29:17.603: ref 0x7fbd4013a170 () -> 32700`
The next call to the same stored proedure cause a SIGSEGV.

2020-12-22 22:39 UTC, wwanderley commented
The reference is decreased on method ObjectType.Close
https://github.com/godror/godror/blob/master/obj.go#L479

2020-12-23 06:53 UTC, tgulacsi requested changes
LGTM, thanks!

2020-12-23 06:53 UTC, tgulacsi approved these changes

2020-12-23 06:54 UTC, merged