Configurable client character set
godror/godror pull request #209
Opened 2022-01-07 15:04 UTC by robstradling

Add a "common" configuration parameter that allows the client character set to be configured.

See #208 for prior discussion.

2022-01-07 15:09 UTC, robstradling commented
@tgulacsi I tried making this a "connection" parameter, but createPool() needs it to be "common".

2022-01-07 19:43 UTC, tgulacsi requested changes
The default should be Charset=="", and not event printing it in the connection string.
Iff it is specified, use it.

2022-01-07 19:43 UTC, tgulacsi commented on dsn/dsn.go
> +	DefaultCharset = "UTF-8"
Not needed.

2022-01-07 19:43 UTC, tgulacsi commented on dsn/dsn.go
> +	q.Add("charset", P.Charset)
guard with 
if P.Charset != ""

2022-01-07 19:43 UTC, tgulacsi commented on dsn/dsn.go
> +	q.Add("charset", P.Charset)
Only if P.Charset != ""

2022-01-07 19:43 UTC, tgulacsi commented on dsn/dsn.go
> +			Charset: DefaultCharset,
not needed. Empty means UTF-8

2022-01-07 19:43 UTC, tgulacsi commented on drv.go
> +	P.encoding = C.CString(charset)
P.encoding, P.nencoding = cUTF8, cUTF8
if charset != "" {
  P.encoding = c.CString(charset)
  P.nencoding = P.encoding
}

2022-01-08 10:26 UTC, tgulacsi approved these changes

2022-01-08 10:27 UTC, merged

2022-01-10 14:42 UTC, robstradling commented
Thanks @tgulacsi !